### ISSUE TITLE
Nuxt.new "Content" ("doc-driven") Stackblitz does not build 

### ISSUE THREAD

**Issue by matej-marjanovic** [nuxt/starter#157]
Going to https://nuxt.new/ and choosing the Content option (`npx nuxi init -t doc-driven app`) on Stackblitz does not start successfully and produces the following errors:

In terminal:
```
✔ Nitro built in 1000 ms                                                                                                                                         nitro 15:08:10
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
[nuxt] [request error] [unhandled] [500] head.addEntry is not a function
  at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
  at async eval (./.nuxt/dev/index.mjs:2686:21)
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
[nuxt] [request error] [unhandled] [500] head.addEntry is not a function
  at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
  at async eval (./.nuxt/dev/index.mjs:2686:21)
[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
```

In website preview:
```
No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage&message=head.addEntry+is+not+a+function&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+eval+(./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+fn+(./node_modules/nuxt/dist/app/nuxt.mjs:148:27)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+Object.callAsync+(./node_modules/unctx/dist/index.mjs:68:19)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+callWithNuxt+(./node_modules/nuxt/dist/app/nuxt.mjs:150:23)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+applyPlugin+(./node_modules/nuxt/dist/app/nuxt.mjs:94:29)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+Module.applyPlugins+(./node_modules/nuxt/dist/app/nuxt.mjs:104:11)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+createNuxtAppServer+(./node_modules/nuxt/dist/app/entry.mjs:30:7)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+%F0%9D%90%9D%F0%9D%90%9E%F0%9D%90%9F%F0%9D%90%9A%F0%9D%90%AE%F0%9D%90%A5%F0%9D%90%AD+(./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Object.renderToString+(./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+eval+(./.nuxt/dev/index.mjs:2686:21)%3C/span%3E%3C/pre%3E&data
```

**Comment by nobkd** [comment]
I tried changing the nuxt version to check when it worked the last time.

With
- `"nuxt": "3.0.0-rc.13"` it throws the error on an unstyled page.
    <details><summary>Page Content</summary>

        No response returned from render handler: /__nuxt_error?url=/&statusCode=500&statusMessage&message=head.addEntry+is+not+a+function&stack=%3Cpre%3E%3Cspan+class=%22stack+internal%22%3Eat+eval+(./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+fn+(./node_modules/nuxt/dist/app/nuxt.mjs:148:27)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+Object.callAsync+(./node_modules/unctx/dist/index.mjs:68:19)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+callWithNuxt+(./node_modules/nuxt/dist/app/nuxt.mjs:150:23)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+applyPlugin+(./node_modules/nuxt/dist/app/nuxt.mjs:94:29)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+Module.applyPlugins+(./node_modules/nuxt/dist/app/nuxt.mjs:104:11)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+createNuxtAppServer+(./node_modules/nuxt/dist/app/entry.mjs:30:7)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+%F0%9D%90%9D%F0%9D%90%9E%F0%9D%90%9F%F0%9D%90%9A%F0%9D%90%AE%F0%9D%90%A5%F0%9D%90%AD+(./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Object.renderToString+(./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+eval+(./.nuxt/dev/index.mjs:636:21)%3C/span%3E%3C/pre%3E&data
    </details>
    <details><summary>Console Content</summary>

        [Vue warn]: Unhandled error during execution of setup function 
          at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
        [Vue warn]: Unhandled error during execution of setup function 
          at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
        [nuxt] [request error] [unhandled] [500] head.addEntry is not a function
          at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
          at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
          at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
          at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
          at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
          at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
          at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
          at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
          at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
          at async eval (./.nuxt/dev/index.mjs:636:21)
        [nuxt] [request error] [unhandled] [500] head.addEntry is not a function
          at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
          at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
          at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
          at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
          at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
          at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
          at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
          at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
          at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
          at async eval (./.nuxt/dev/index.mjs:636:21)
        [Vue warn]: Unhandled error during execution of setup function 
          at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
        [Vue warn]: Unhandled error during execution of setup function 
          at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
    </details>
- `"nuxt": "3.0.0-rc.12"` & `"nuxt": "npm:nuxt3@latest"` it throws the error on a correctly displayed error page.
    <details><summary>Page Content</summary>

      500
      head.addEntry is not a function
      
      at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)
      at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)
      at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)
      at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)
      at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)
      at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)
      at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)
      at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)
      at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)
      at async eval (./.nuxt/dev/index.mjs:624:21)
    </details>
    <details><summary>Console Content</summary>

      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
      [nuxt] [request error] [unhandled] [500] head.addEntry is not a function
        at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
        at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
        at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
        at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
        at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
        at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
        at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
        at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
        at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
        at async eval (./.nuxt/dev/index.mjs:624:21)
      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
      [nuxt] [request error] [unhandled] [500] head.addEntry is not a function
        at eval (./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8)  
        at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)  
        at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:19)  
        at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)  
        at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)  
        at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)  
        at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)  
        at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
        at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
        at async eval (./.nuxt/dev/index.mjs:624:21)
      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
      [Vue warn]: Unhandled error during execution of setup function 
        at <ErrorDev statusCode=500 statusMessage="" description="head.addEntry is not a function"  ... >
    </details>
- `"nuxt": "3.0.0-rc.11"` the *doc-driven / v3 starter* works without any problems.

**All of this happens  to v3 starter on Stackblitz as well.**

**Comment by matej-marjanovic** [comment]
Appears to be fixed now that it uses rc.14. Using the doc-driven template on nuxt.new now works again 👍  https://stackblitz.com/github/nuxt/starter/tree/doc-driven
