### ISSUE TITLE
error: yarn prepack

### ISSUE THREAD

**Issue by HomWang** [nuxt/starter#58]
1. yarn prepack

error:

```js
error TS5083: Cannot read file '/Users/hom/home/NuxtUI/playground/.nuxt/tsconfig.json'.

src/module.ts(3,45): error TS2792: Cannot find module '@nuxt/kit'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/module.ts(19,61): error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.

Error: Failed to compile. Check the logs above.
    at error (file:///Users/hom/home/NuxtUI/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///Users/hom/home/NuxtUI/node_modules/rollup/dist/es/shared/rollup.js:21807:12)
    at Object.error (file:///Users/hom/home/NuxtUI/node_modules/rollup/dist/es/shared/rollup.js:22530:20)
    at Object.error (file:///Users/hom/home/NuxtUI/node_modules/rollup/dist/es/shared/rollup.js:21984:42)
    at Object.transform (file:///Users/hom/home/NuxtUI/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1590:26)
    at file:///Users/hom/home/NuxtUI/node_modules/rollup/dist/es/shared/rollup.js:22739:37
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  id: '/Users/hom/home/NuxtUI/src/module.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [ '/Users/hom/home/NuxtUI/src/module.ts' ]
}
```

**Comment by HomWang** [comment]
test:
error: use yarn and pnpm
success: use npm
