### ISSUE TITLE
我拉取了模版，尝试运行了一下，然后去页面中刷新了一下，报错了以下问题：

### ISSUE THREAD

**Issue by abucd** [nuxt/starter#680]
ERROR  Internal server error: [postcss] C:/Users/21911/Desktop/全栈前端/全栈前端/starter-3/app.vue?vue&type=style&index=0&lang.css:1:1: Unknown word                                          15:05:05  
  Plugin: vite:css
  File: C:/Users/21911/Desktop/全栈前端/全栈前端/starter-3/app.vue?vue&type=style&index=0&lang.css:1:0
  1  |  <template>
     |  ^
  2  |    <div>
  3  |      
      at Input.error (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\input.js:106:16)
      at Parser.unknownWord (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\parser.js:593:22)
      at Parser.other (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\parser.js:435:12)
      at Parser.parse (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\parser.js:470:16)
      at parse (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\parse.js:11:12)
      at new LazyResult (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\lazy-result.js:133:16)
      at Processor.process (C:\Users\21911\Desktop\全栈前端\全栈前端\starter-3\node_modules\.pnpm\postcss@8.4.35\node_modules\postcss\lib\processor.js:53:14)
      at compileCSS (file:///C:/Users/21911/Desktop/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/starter-3/node_modules/.pnpm/vite@5.1.5/node_modules/vite/dist/node/chunks/dep-G-px366b.js:32012:63)
      at async TransformContext.transform (file:///C:/Users/21911/Desktop/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/starter-3/node_modules/.pnpm/vite@5.1.5/node_modules/vite/dist/node/chunks/dep-G-px366b.js:31327:56)
      at async file:///C:/Users/21911/Desktop/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/%E5%85%A8%E6%A0%88%E5%89%8D%E7%AB%AF/starter-3/node_modules/.pnpm/vite-plugin-inspect@0.8.3_@nuxt+kit@3.10.3_vite@5.1.5/node_modules/vite-plugin-inspect/dist/index.mjs:377:17

**Comment by abucd** [comment]
我查找了一下端口3000，找不到任何进程，
我又去浏览器查看了一下本地端口3000，
页面被nuxt占领了，但是没有样式，
我又重新打开了一下浏览器，依旧如此。
我又dev了一下，还是3000端口，
我在vscode中打开了2个终端，再次dev了一下，
发现3001的本地端口没有任何问题。
我决定不使用3000端口了

**Comment by abucd** [comment]
我查找了一下端口3000，找不到任何进程，
我又去浏览器查看了一下本地端口3000，
页面被nuxt占领了，但是没有样式，
我又重新打开了一下浏览器，依旧如此。
我又dev了一下，还是3000端口，
我在vscode中打开了2个终端，再次dev了一下，
发现3001的本地端口没有任何问题。
我决定不使用3000端口了。
