### ISSUE TITLE
Cannot start nuxt:  Package subpath './nuxt' is not defined by "exports"

### ISSUE THREAD

**Issue by jclaessens97** [nuxt/starter#90]
I setup a nuxt module following the (limited) [docs](https://v3.nuxtjs.org/guide/going-further/modules/) and the [module starter template](https://github.com/nuxt/starter/tree/module). 

The playground works, but whenever I want to build and use it in my main nuxt application (using pnpm and `file:../ui`), I get following error output:

```
Nuxt CLI v3.0.0-rc.8                                                  09:15:59
                                                                      09:16:02
  > Local:    http://localhost:8080/
  > Network:  http://10.11.12.43:8080/


 ERROR  Cannot start nuxt:  Package subpath './nuxt' is not defined by "exports" in /Users/jclaessens/dev/proj/packages/nuxt3_web/node_modules/@skyebase/ui/package.json

  at new NodeError (node:internal/errors:371:5)
  at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
  at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
  at resolveExports (node:internal/modules/cjs/loader:482:36)
  at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (/Users/jclaessens/dev/proj/node_modules/.pnpm/jiti@1.14.0/node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (/Users/jclaessens/dev/proj/node_modules/.pnpm/@nuxt+kit@3.0.0-rc.8_webpack@5.74.0/node_modules/@nuxt/kit/dist/index.mjs:253:29)
  at normalizeModule (/Users/jclaessens/dev/proj/node_modules/.pnpm/@nuxt+kit@3.0.0-rc.8_webpack@5.74.0/node_modules/@nuxt/kit/dist/index.mjs:462:18)
```

`npx nuxi info` output:

```
❯ npx nuxi info
Nuxt CLI v3.0.0-rc.8                                                                                                                                                                  09:30:16
RootDir: /Users/jclaessens/dev/skyebase/i-spect/packages/nuxt3_web                                                                                                                    09:30:18
Nuxt project info:                                                                                                                                                                    09:30:18

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `ssr`, `typescript`, `css`, `modules`, `runtimeConfig`
- Runtime Modules:  `@vueuse/nuxt@8.9.4`, `proj/nuxt@1.0.0`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                                      09:30:18

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org
```

I configured the module as `proj/ui/nuxt` and I'm sure I build it first using the `prepack` command.

Any pointers on what it could be?

**Comment by danielroe** [comment]
Impossible to say exactly without seeing your code, but you likely need to add a subpath exports like:

```json
  "exports": {
    // ...
    "./nuxt": "./dist/nuxt.mjs"
  },
```

See more at https://nodejs.org/api/packages.html#packages_subpath_exports.

**Comment by jclaessens97** [comment]
Thanks for your answer.
I can try to make a minimal repro later today if it's something that hasn't come up yet...

As for the exports I just used the "main" and direct it to the built module files:
```
"type": "module",
  "exports": {
    ".": {
      "import": "./dist/module.mjs",
      "require": "./dist/module.cjs"
    }
  },
  "main": "./dist/module.cjs",
  "types": "./dist/types.d.ts",
  "files": [
    "dist"
  ],
```

My module.ts looks like this:

```
import {
  defineNuxtModule,
  addComponentsDir,
  addPlugin,
  createResolver,
} from '@nuxt/kit';

export default defineNuxtModule({
  meta: {
    name: '@skyebase/ui',
    compatibility: {
      nuxt: '^3.0.0',
    },
  },
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url);

    nuxt.options.css = [
      'primevue/resources/themes/md-light-deeppurple/theme.css',
      'primevue/resources/primevue.min.css',
      'primeicons/primeicons.css',
      'primeflex/primeflex.css',
      ...nuxt.options.css,
    ];
    nuxt.options.build.transpile.push('primevue');

    const pluginDir = resolve(__dirname, 'runtime', 'plugins');
    addPlugin(resolve(pluginDir, 'vue-country-flag.plugin.ts'));
    addPlugin(resolve(pluginDir, 'mapbox.plugin.ts'));
    addPlugin(resolve(pluginDir, 'primevue.plugin.ts'));
    addPlugin(resolve(pluginDir, 'primevue.plugin.client.ts'));

    addComponentsDir({
      path: resolve(__dirname, 'runtime', 'components'),
      prefix: 'sb',
    });
  },
});
```

And then runtime contains just plugins and components using primevue as plain vue/nuxt code.

If you still need more info to investigate, please let me know then I'll try to setup a minimal repro.

**Comment by danielroe** [comment]
Yes, a reproduction would be helpful, thanks.
